services:
  database:
    image: postgres
    container_name: prediction_tracker_database
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: prediction-tracker
      POSTGRES_USER: pythia
      POSTGRES_PASSWORD: delphi
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
        - postgres
    restart: unless-stopped
  pgadmin:
    container_name: prediction_tracker_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: philip@thebakery.io
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
        - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
